import os
import re
import requests
from pathlib import Path
from dotenv import load_dotenv

from . import usage_tracker

load_dotenv()

PEXELS_API_KEY = os.getenv("PEXELS_API_KEY")
PEXELS_SEARCH_URL = "https://api.pexels.com/videos/search"

PIXABAY_API_KEY = os.getenv("PIXABAY_API_KEY")
PIXABAY_SEARCH_URL = "https://pixabay.com/api/videos/"

TARGET_WIDTH = 1080
TARGET_HEIGHT = 1920

# Expanded stopwords list to aggressively strip cinematic descriptors
STOPWORDS = {
    "a", "an", "the", "of", "to", "in", "on", "at", "with", "and", "or",
    "show", "display", "illustrate", "captioned", "before", "into", "while",
    "cinematic", "drone", "shot", "footage", "descending", "over", "background",
    "close", "up", "closeup", "rich", "dark", "large", "circular", "high",
    "aerial", "view", "showing", "slow", "motion", "panoramic", "camera", "moving",
    "person", "people", "applying", "stark", "crusted"
}

# Best-effort filter for likely AI-generated Pixabay content.
AI_TAG_MARKERS = [
    "ai generated", "ai-generated", "generated by ai", "artificial intelligence",
    "midjourney", "stable diffusion", "dall-e", "dalle", "ai video", "ai art",
]


class FootageError(Exception):
    pass


# ---------------------------------------------------------------------------
# Query extraction
# ---------------------------------------------------------------------------

def extract_search_query(visual_prompt: str, max_words: int = 3) -> str:
    """
    Strips the 'captioned: ...' clause, removes descriptive fluff and stopwords,
    and returns 2-3 core search terms suitable for stock APIs.
    """
    text = re.split(r",?\s*captioned:", visual_prompt, flags=re.IGNORECASE)[0]
    text = re.sub(r"[^\w\s]", "", text)
    words = [w for w in text.lower().split() if w not in STOPWORDS]
    return " ".join(words[:max_words]) if words else visual_prompt[:30]


def extract_topic_query(topic: str) -> str:
    """Bare topic name, used as a loose/broad fallback query."""
    text = re.sub(r"[^\w\s]", "", topic)
    words = [w for w in text.lower().split() if w not in STOPWORDS]
    return " ".join(words[:3]) if words else topic


def _relevance_terms(topic_query: str) -> set:
    """Derives simple relevance terms from a topic query."""
    terms = set()
    for w in topic_query.split():
        terms.add(w)
        if w.endswith("s") and len(w) > 3:
            terms.add(w[:-1])
    return terms


def _is_relevant(text: str, terms: set) -> bool:
    if not terms:
        return True  # no terms available, skip filtering
    text = (text or "").lower()
    return any(term in text for term in terms)


# ---------------------------------------------------------------------------
# Pexels
# ---------------------------------------------------------------------------

def _pick_best_pexels_file(video_files: list) -> dict | None:
    """Prefer portrait files closest to TARGET_WIDTH x TARGET_HEIGHT."""
    if not video_files:
        return None

    def score(f):
        return abs(f.get("width", 0) - TARGET_WIDTH) + abs(f.get("height", 0) - TARGET_HEIGHT)

    portrait_files = [f for f in video_files if f.get("height", 0) > f.get("width", 0)]
    if portrait_files:
        return min(portrait_files, key=score)

    return min(video_files, key=score)


def search_pexels(query: str, per_page: int = 5, fact_number: int | None = None) -> list:
    if not PEXELS_API_KEY:
        return []

    headers = {"Authorization": PEXELS_API_KEY}
    params = {"query": query, "orientation": "portrait", "per_page": per_page}

    response = requests.get(PEXELS_SEARCH_URL, headers=headers, params=params, timeout=30)
    usage_tracker.log_call("pexels", fact_number=fact_number)
    if response.status_code != 200:
        raise FootageError(f"Pexels API error {response.status_code}: {response.text[:300]}")

    return response.json().get("videos", [])


def _download_from_pexels(
    query: str, exclude_ids: set, out_path: Path, relevance_terms: set = None, fact_number: int | None = None
) -> dict | None:
    videos = search_pexels(query, fact_number=fact_number)

    for video in videos:
        namespaced_id = f"pexels:{video.get('id')}"
        if namespaced_id in exclude_ids:
            continue
        if relevance_terms and not _is_relevant(video.get("url", ""), relevance_terms):
            continue
        best_file = _pick_best_pexels_file(video.get("video_files", []))
        if not best_file:
            continue

        video_response = requests.get(best_file["link"], timeout=60)
        if video_response.status_code != 200:
            continue

        with open(out_path, "wb") as f:
            f.write(video_response.content)

        return {
            "source": "pexels",
            "query": query,
            "path": str(out_path),
            "source_video_id": namespaced_id,
            "source_url": video.get("url"),
            "width": best_file.get("width"),
            "height": best_file.get("height"),
        }

    return None


# ---------------------------------------------------------------------------
# Pixabay
# ---------------------------------------------------------------------------

def _is_likely_ai_generated(hit: dict) -> bool:
    tags = hit.get("tags", "").lower()
    return any(marker in tags for marker in AI_TAG_MARKERS)


def search_pixabay(query: str, per_page: int = 5, fact_number: int | None = None) -> list:
    if not PIXABAY_API_KEY:
        return []

    params = {
        "key": PIXABAY_API_KEY,
        "q": query,
        "per_page": max(per_page, 3),
        "safesearch": "true",
    }

    response = requests.get(PIXABAY_SEARCH_URL, params=params, timeout=30)
    usage_tracker.log_call("pixabay", fact_number=fact_number)
    if response.status_code != 200:
        raise FootageError(f"Pixabay API error {response.status_code}: {response.text[:300]}")

    hits = response.json().get("hits", [])
    return [h for h in hits if not _is_likely_ai_generated(h)]


def _pick_best_pixabay_rendition(hit: dict) -> dict | None:
    videos = hit.get("videos", {})
    for size in ("medium", "large", "small", "tiny"):
        rendition = videos.get(size)
        if rendition and rendition.get("url"):
            return {
                "url": rendition["url"],
                "width": rendition.get("width"),
                "height": rendition.get("height"),
            }
    return None


def _download_from_pixabay(
    query: str, exclude_ids: set, out_path: Path, relevance_terms: set = None, fact_number: int | None = None
) -> dict | None:
    hits = search_pixabay(query, fact_number=fact_number)

    for hit in hits:
        namespaced_id = f"pixabay:{hit.get('id')}"
        if namespaced_id in exclude_ids:
            continue
        if relevance_terms and not _is_relevant(hit.get("tags", ""), relevance_terms):
            continue
        rendition = _pick_best_pixabay_rendition(hit)
        if not rendition:
            continue

        video_response = requests.get(rendition["url"], timeout=60)
        if video_response.status_code != 200:
            continue

        with open(out_path, "wb") as f:
            f.write(video_response.content)

        return {
            "source": "pixabay",
            "query": query,
            "path": str(out_path),
            "source_video_id": namespaced_id,
            "source_url": hit.get("pageURL"),
            "width": rendition.get("width"),
            "height": rendition.get("height"),
        }

    return None


# ---------------------------------------------------------------------------
# Waterfall: Pixabay (specific) -> Pexels (specific) -> Fallbacks
# ---------------------------------------------------------------------------

def download_footage_for_prompt(
    visual_prompt: str,
    output_path: str,
    exclude_ids: set = None,
    topic_fallback_query: str = None,
    video_id: int | None = None,
) -> dict:
    """
    Cascade download strategy with clean keywords and layered fallbacks:
      1. Pixabay with cleaned query from prompt (topic relevance checked)
      2. Pexels with cleaned query from prompt (topic relevance checked)
      3. Pixabay with broad topic fallback query (no strict relevance check)
      4. Pexels with broad topic fallback query (no strict relevance check)
      5. Generic fallback ("nature landscape") to guarantee run completion

    video_id (the pipeline's fact_number for the WHOLE video, not the
    within-video fact index) is passed through to usage_tracker so
    ElevenLabs/Pexels/Pixabay calls can be correlated back to a video.
    """
    exclude_ids = exclude_ids or set()
    query = extract_search_query(visual_prompt)
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    relevance_terms = _relevance_terms(topic_fallback_query) if topic_fallback_query else None

    # Step 1: Specific query on Pixabay
    result = _download_from_pixabay(query, exclude_ids, output_path, relevance_terms, fact_number=video_id)
    if result:
        return result

    # Step 2: Specific query on Pexels
    result = _download_from_pexels(query, exclude_ids, output_path, relevance_terms, fact_number=video_id)
    if result:
        return result

    # Step 3 & 4: Fallback to topic query (dropping strict relevance check)
    if topic_fallback_query:
        result = _download_from_pixabay(
            topic_fallback_query, exclude_ids, output_path, relevance_terms=None, fact_number=video_id
        )
        if result:
            return result

        result = _download_from_pexels(
            topic_fallback_query, exclude_ids, output_path, relevance_terms=None, fact_number=video_id
        )
        if result:
            return result

    # Step 5: Absolute fallback to generic scenery
    for generic_query in ("nature landscape", "scenery"):
        result = _download_from_pexels(
            generic_query, exclude_ids, output_path, relevance_terms=None, fact_number=video_id
        )
        if result:
            return result
        result = _download_from_pixabay(
            generic_query, exclude_ids, output_path, relevance_terms=None, fact_number=video_id
        )
        if result:
            return result

    raise FootageError(
        f"No relevant footage found on Pixabay or Pexels for query: '{query}' "
        f"(from prompt: '{visual_prompt}')"
    )


def download_footage_for_script(script: dict, output_dir: str, max_retries: int = 1) -> dict:
    """Downloads footage for every fact in a script."""
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    results = []
    failures = []
    used_video_ids = set()

    topic_fallback_query = extract_topic_query(script["topic"])
    video_id = script.get("fact_number")  # the whole-video identifier, for usage tracking

    for fact in script["facts"]:
        fact_num = fact["number"]
        out_path = output_dir / f"fact{fact_num}.mp4"

        attempt = 0
        last_error = None
        while attempt <= max_retries:
            try:
                result = download_footage_for_prompt(
                    fact["visual_prompt"],
                    str(out_path),
                    exclude_ids=used_video_ids,
                    topic_fallback_query=topic_fallback_query,
                    video_id=video_id,
                )
                result["fact_number"] = fact_num
                results.append(result)
                used_video_ids.add(result["source_video_id"])
                last_error = None
                break
            except FootageError as e:
                last_error = str(e)
                attempt += 1

        if last_error:
            failures.append({"fact_number": fact_num, "error": last_error})

    return {
        "downloaded": results,
        "failures": failures,
        "total_facts": len(script["facts"]),
        "success_count": len(results),
    }