import os
import re
import requests
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

PEXELS_API_KEY = os.getenv("PEXELS_API_KEY")
PEXELS_SEARCH_URL = "https://api.pexels.com/videos/search"

PIXABAY_API_KEY = os.getenv("PIXABAY_API_KEY")
PIXABAY_SEARCH_URL = "https://pixabay.com/api/videos/"

TARGET_WIDTH = 1080
TARGET_HEIGHT = 1920

STOPWORDS = {
    "a", "an", "the", "of", "to", "in", "on", "at", "with", "and", "or",
    "show", "display", "illustrate", "captioned", "before", "into", "while",
}

# Best-effort filter for likely AI-generated Pixabay content. Pixabay's
# official API has no dedicated AI-content flag, so this checks tags for
# common AI-generation terms. Not guaranteed to catch everything.
AI_TAG_MARKERS = [
    "ai generated", "ai-generated", "generated by ai", "artificial intelligence",
    "midjourney", "stable diffusion", "dall-e", "dalle", "ai video", "ai art",
]


class FootageError(Exception):
    pass


# ---------------------------------------------------------------------------
# Query extraction
# ---------------------------------------------------------------------------

def extract_search_query(visual_prompt: str, max_words: int = 5) -> str:
    """
    TEMPORARY stopgap query extractor. Strips the 'captioned: ...' clause,
    removes stopwords, and takes the first few meaningful words.
    """
    text = re.split(r",?\s*captioned:", visual_prompt, flags=re.IGNORECASE)[0]
    text = re.sub(r"[^\w\s]", "", text)
    words = [w for w in text.lower().split() if w not in STOPWORDS]
    return " ".join(words[:max_words]) if words else visual_prompt[:40]


def extract_topic_query(topic: str) -> str:
    """Bare topic name, used as a loose/broad fallback query."""
    text = re.sub(r"[^\w\s]", "", topic)
    words = [w for w in text.lower().split() if w not in STOPWORDS]
    return " ".join(words) if words else topic

def _relevance_terms(topic_query: str) -> set:
    """Derives simple relevance terms from a topic query — each word plus
    a naive singular form, used to verify a search result is actually
    about the topic before accepting it."""
    terms = set()
    for w in topic_query.split():
        terms.add(w)
        if w.endswith("s") and len(w) > 3:
            terms.add(w[:-1])
    return terms


def _is_relevant(text: str, terms: set) -> bool:
    if not terms:
        return True  # no terms available, skip filtering
    text = (text or "").lower()
    return any(term in text for term in terms)


# ---------------------------------------------------------------------------
# Pexels
# ---------------------------------------------------------------------------

def _pick_best_pexels_file(video_files: list) -> dict | None:
    """Prefer portrait files closest to TARGET_WIDTH x TARGET_HEIGHT.
    Falls back to the best available landscape file if no portrait exists."""
    if not video_files:
        return None

    def score(f):
        return abs(f.get("width", 0) - TARGET_WIDTH) + abs(f.get("height", 0) - TARGET_HEIGHT)

    portrait_files = [f for f in video_files if f.get("height", 0) > f.get("width", 0)]
    if portrait_files:
        return min(portrait_files, key=score)

    return min(video_files, key=score)


def search_pexels(query: str, per_page: int = 5) -> list:
    if not PEXELS_API_KEY:
        return []  # Pexels optional if not configured

    headers = {"Authorization": PEXELS_API_KEY}
    params = {"query": query, "orientation": "portrait", "per_page": per_page}

    response = requests.get(PEXELS_SEARCH_URL, headers=headers, params=params, timeout=30)
    if response.status_code != 200:
        raise FootageError(f"Pexels API error {response.status_code}: {response.text[:300]}")

    return response.json().get("videos", [])


def _download_from_pexels(query: str, exclude_ids: set, out_path: Path, relevance_terms: set = None) -> dict | None:
    videos = search_pexels(query)

    for video in videos:
        namespaced_id = f"pexels:{video.get('id')}"
        if namespaced_id in exclude_ids:
            continue
        if not _is_relevant(video.get("url", ""), relevance_terms):
            continue
        best_file = _pick_best_pexels_file(video.get("video_files", []))
        if not best_file:
            continue

        video_response = requests.get(best_file["link"], timeout=60)
        if video_response.status_code != 200:
            continue

        with open(out_path, "wb") as f:
            f.write(video_response.content)

        return {
            "source": "pexels",
            "query": query,
            "path": str(out_path),
            "source_video_id": namespaced_id,
            "source_url": video.get("url"),
            "width": best_file.get("width"),
            "height": best_file.get("height"),
        }

    return None


# ---------------------------------------------------------------------------
# Pixabay (primary source — better niche/animal coverage than Pexels)
# ---------------------------------------------------------------------------

def _is_likely_ai_generated(hit: dict) -> bool:
    tags = hit.get("tags", "").lower()
    return any(marker in tags for marker in AI_TAG_MARKERS)


def search_pixabay(query: str, per_page: int = 5) -> list:
    """
    Pixabay video search. No orientation filter on this endpoint — all
    results are landscape. No dedicated AI-content flag either; results
    are filtered by a best-effort tag check instead.
    """
    if not PIXABAY_API_KEY:
        return []  # Pixabay optional if not configured

    params = {
        "key": PIXABAY_API_KEY,
        "q": query,
        "per_page": max(per_page, 3),  # Pixabay requires per_page >= 3
        "safesearch": "true",
    }

    response = requests.get(PIXABAY_SEARCH_URL, params=params, timeout=30)
    if response.status_code != 200:
        raise FootageError(f"Pixabay API error {response.status_code}: {response.text[:300]}")

    hits = response.json().get("hits", [])
    return [h for h in hits if not _is_likely_ai_generated(h)]


def _pick_best_pixabay_rendition(hit: dict) -> dict | None:
    """Prefers 'medium' (usually 1920x1080); falls back through other sizes."""
    videos = hit.get("videos", {})
    for size in ("medium", "large", "small", "tiny"):
        rendition = videos.get(size)
        if rendition and rendition.get("url"):
            return {
                "url": rendition["url"],
                "width": rendition.get("width"),
                "height": rendition.get("height"),
            }
    return None


def _download_from_pixabay(query: str, exclude_ids: set, out_path: Path, relevance_terms: set = None) -> dict | None:
    hits = search_pixabay(query)

    for hit in hits:
        namespaced_id = f"pixabay:{hit.get('id')}"
        if namespaced_id in exclude_ids:
            continue
        if not _is_relevant(hit.get("tags", ""), relevance_terms):
            continue
        rendition = _pick_best_pixabay_rendition(hit)
        if not rendition:
            continue

        video_response = requests.get(rendition["url"], timeout=60)
        if video_response.status_code != 200:
            continue

        with open(out_path, "wb") as f:
            f.write(video_response.content)

        return {
            "source": "pixabay",
            "query": query,
            "path": str(out_path),
            "source_video_id": namespaced_id,
            "source_url": hit.get("pageURL"),
            "width": rendition.get("width"),
            "height": rendition.get("height"),
        }

    return None


# ---------------------------------------------------------------------------
# Unified waterfall: Pixabay (specific) -> Pexels (specific) -> Pixabay (loose)
# ---------------------------------------------------------------------------

def download_footage_for_prompt(
    visual_prompt: str,
    output_path: str,
    exclude_ids: set = None,
    topic_fallback_query: str = None,
) -> dict:
    """
    Fully automated, no manual steps. Every candidate is checked for
    topic relevance before being accepted — an unrelated animal/clip
    is treated the same as no result at all, rather than being used
    as a silent substitute. Priority order per fact:
      1. Pixabay, specific query extracted from the visual prompt.
      2. Pexels, same specific query.
      3. Pixabay again, with a loose/broad query (just the topic name).
    If nothing relevant is found anywhere, this fact fails explicitly.
    """
    exclude_ids = exclude_ids or set()
    query = extract_search_query(visual_prompt)
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    relevance_terms = _relevance_terms(topic_fallback_query) if topic_fallback_query else None

    result = _download_from_pixabay(query, exclude_ids, output_path, relevance_terms)
    if result:
        return result

    result = _download_from_pexels(query, exclude_ids, output_path, relevance_terms)
    if result:
        return result

    if topic_fallback_query:
        result = _download_from_pixabay(topic_fallback_query, exclude_ids, output_path, relevance_terms)
        if result:
            return result

    raise FootageError(
        f"No relevant footage found on Pixabay or Pexels for query: '{query}' "
        f"(from prompt: '{visual_prompt}')"
    )


def download_footage_for_script(script: dict, output_dir: str, max_retries: int = 1) -> dict:
    """
    Downloads footage for every fact in a parsed script, fully automated
    (no manual overrides). Tracks used source video IDs across facts to
    avoid repeating the same clip when a topic has thin coverage.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    results = []
    failures = []
    used_video_ids = set()

    topic_fallback_query = extract_topic_query(script["topic"])

    for fact in script["facts"]:
        fact_num = fact["number"]
        out_path = output_dir / f"fact{fact_num}.mp4"

        attempt = 0
        last_error = None
        while attempt <= max_retries:
            try:
                result = download_footage_for_prompt(
                    fact["visual_prompt"],
                    str(out_path),
                    exclude_ids=used_video_ids,
                    topic_fallback_query=topic_fallback_query,
                )
                result["fact_number"] = fact_num
                results.append(result)
                used_video_ids.add(result["source_video_id"])
                last_error = None
                break
            except FootageError as e:
                last_error = str(e)
                attempt += 1

        if last_error:
            failures.append({"fact_number": fact_num, "error": last_error})

    return {
        "downloaded": results,
        "failures": failures,
        "total_facts": len(script["facts"]),
        "success_count": len(results),
    }